services:
  - type: web
    name: ai-resume-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python3 -m spacy download en_core_web_sm
    startCommand: python3 app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: True
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: http://localhost:3000
