services:
  - type: web
    name: ai-resume-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
